FROM debian:11
COPY ./sql /var/lib/mysql
RUN apt update && timedatectl set-timezone Europe/Minsk && apt install -y apache2 mariadb-server php libapache2-mod-php php-mysql lsb-release gnupg2 && touch /etc/apt/sources.list.d/zoneminder.list && chmo>
